version: 2.1

jobs:
  build:
    docker:
      - image: golang:1.18-alpine
    working_directory: /go/src/Mission-Control-Operator
    steps:
      - checkout
      - run: go install github.com/holy-tech/Mission-Control-Operator
  lint:
    docker:
      - image: golangci/golangci-lint:v1.53-alpine
    steps:
      - checkout
      - run: golangci-lint run
  test:
    docker:
      - image: golang:1.18
    working_directory: /go/src/Mission-Control-Operator
    steps:
      - checkout
      - run: go test -v -race ./...

workflows:
  build_lint_test:
    jobs:
      - build
      - lint
      - test