apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mission-editor-role
rules:
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missions/status
  verbs:
  - get
