---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - compute.mission-control.apis.io
  resources:
  - virtualmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - compute.mission-control.apis.io
  resources:
  - virtualmachines/finalizers
  verbs:
  - update
- apiGroups:
  - compute.mission-control.apis.io
  resources:
  - virtualmachines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missionkeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missionkeys/finalizers
  verbs:
  - update
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missionkeys/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missions/finalizers
  verbs:
  - update
- apiGroups:
  - mission.mission-control.apis.io
  resources:
  - missions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - storage.mission-control.apis.io
  resources:
  - storagebuckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.mission-control.apis.io
  resources:
  - storagebuckets/finalizers
  verbs:
  - update
- apiGroups:
  - storage.mission-control.apis.io
  resources:
  - storagebuckets/status
  verbs:
  - get
  - patch
  - update
