## Append samples of your project ##
resources:
- mission_v1alpha1_mission.yaml
- mission_v1alpha1_missionkey.yaml
- compute_v1alpha1_virtualmachine.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
