apiVersion: mission.mission-control.apis.io/v1alpha1
kind: MissionKey
metadata:
  labels:
    app.kubernetes.io/name: missionkey
    app.kubernetes.io/instance: missionkey-sample
    app.kubernetes.io/part-of: mission-control-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: mission-control-operator
  name: missionkey-sample
spec:
  # TODO(user): Add fields here
