resources:
- bases/mission.mission-control.apis.io_missions.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
#- patches/webhook_in_missions.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

#- patches/cainjection_in_missions.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

configurations:
- kustomizeconfig.yaml
